version: '3.8'

services:
  garda-identitas:
    build: .
    container_name: garda-identitas
    ports:
      - "8888:80" # Mapping Port Host 8888 -> Port Container 80
    volumes:
      - ./:/usr/share/nginx/html # Hot Reload: Mapping folder saat ini ke folder Nginx
    restart: unless-stopped
